from collections.abc import Sequence
from typing import Any, final

import numpy as np
from mefikit.mefipy.sel import Selection
from numpy.typing import NDArray
from typing_extensions import TypeAlias

# Regular connectivity: 2D array (n_elements, nodes_per_element)
# Poly connectivity: (data, offsets) for variable-node elements
Connectivity: TypeAlias = NDArray[np.intp] | tuple[NDArray[np.intp], NDArray[np.intp]]

# Anything that can be implicitly converted to a Field
FieldLike: TypeAlias = Field | str | float | NDArray[np.float64] | list[float]

@final
class Field:
    """Symbolic field expression that can be evaluated on a mesh."""

    def __new__(cls, value: FieldLike) -> Field: ...

    # --- Arithmetic ---
    def __add__(self, other: FieldLike, /) -> Field: ...
    def __radd__(self, other: FieldLike, /) -> Field: ...
    def __rdiv__(self, other: FieldLike, /) -> Field: ...
    def __sub__(self, other: FieldLike, /) -> Field: ...
    def __rsub__(self, other: FieldLike, /) -> Field: ...
    def __mul__(self, other: FieldLike, /) -> Field: ...
    def __rmul__(self, other: FieldLike, /) -> Field: ...

    # --- Comparisons (produce Selections) ---
    def __gt__(self, other: FieldLike, /) -> Selection: ...
    def __ge__(self, other: FieldLike, /) -> Selection: ...
    def __lt__(self, other: FieldLike, /) -> Selection: ...
    def __le__(self, other: FieldLike, /) -> Selection: ...

    # --- Math functions ---
    def abs(self) -> Field: ...
    def exp(self) -> Field: ...
    def ln(self) -> Field: ...
    def log10(self) -> Field: ...
    def sqrt(self) -> Field: ...
    def square(self) -> Field: ...
    def sin(self) -> Field: ...
    def cos(self) -> Field: ...
    def tan(self) -> Field: ...

@final
class UMesh:
    """Unstructured mesh with optional nodal/element fields."""

    def __new__(cls, coords: NDArray[np.float64]) -> UMesh: ...

    # --- Coordinates & connectivity ---
    def coords(self) -> NDArray[np.float64]: ...
    def block_types(self) -> list[str]: ...
    def blocks(self) -> dict[str, Connectivity]: ...
    def fields(self) -> dict[str, dict[str, NDArray[np.float64]]]: ...

    # --- Serialisation ---
    def to_json(self) -> str: ...
    def to_json_pretty(self) -> str: ...
    @staticmethod
    def read(path: str) -> UMesh: ...
    def write(self, path: str) -> None: ...

    # --- Modification ---
    def add_regular_block(
        self,
        et: str,
        block: NDArray[np.intp],
        fields: dict[str, NDArray[np.float64]] | None = ...,
    ) -> None: ...
    def merge_nodes(self, eps: float = ...) -> UMesh: ...
    def snap(self, reference: UMesh, eps: float = ...) -> UMesh: ...
    def crack(self, cut_mesh: UMesh) -> UMesh: ...

    # --- Extrusion ---
    def extrude(self, along: Sequence[float]) -> UMesh: ...
    def extrude_parallel(self, along: NDArray[np.float64]) -> UMesh: ...
    def extrude_curv(self, along: NDArray[np.float64]) -> UMesh: ...

    # --- Topology ---
    def descend(
        self,
        src_dim: int | None = ...,
        target_dim: int | None = ...,
    ) -> UMesh: ...
    def descend_update(
        self,
        src_dim: int | None = ...,
        target_dim: int | None = ...,
    ) -> UMesh | None: ...
    def boundaries(
        self,
        src_dim: int | None = ...,
        target_dim: int | None = ...,
    ) -> UMesh: ...
    def boundaries_update(
        self,
        src_dim: int | None = ...,
        target_dim: int | None = ...,
    ) -> UMesh | None: ...
    def connected_components(
        self,
        src_dim: int | None = ...,
        link_dim: int | None = ...,
        with_fields: bool = ...,
    ) -> list[UMesh]: ...

    # --- Measurement ---
    def measure(self) -> dict[str, NDArray[np.float64]]: ...
    def measure_update(self) -> None: ...

    # --- Field evaluation ---
    def select(self, expr: Selection, with_fields: bool = ...) -> UMesh: ...
    def eval(self, expr: Field) -> dict[str, NDArray[np.float64]]: ...
    def eval_update(self, name: str, expr: Field) -> None: ...
    @staticmethod
    def to_pyvista(
        umesh: UMesh,
        dim: str | int | None = ...,
        with_fields: Sequence[str] | bool = ...,
    ): ...

def build_cmesh(*args: Any) -> UMesh: ...

__all__ = ["Field", "UMesh", "build_cmesh"]
