[changelog]
header = """# CHANGELOG

All notable changes to this project will be documented in this file.

"""
commit_parsers = [
  { message = "^feat", group = "Add" },
  { message = "^fix", group = "Fix" },
  { message = "^perf", group = "Performance" },
  { message = "^docs", group = "Documentation" },
  { message = "^refactor", group = "Refactor" },
  { message = "^test", group = "Test" },
  { message = "^.*", group = "Other" },
]

[workspace]
git_tag_enable = false
git_release_enable = false

[[package]]
name = "mefikit"
version_group = "mefikit"
changelog_path = "CHANGELOG.md"
changelog_include = ["mefipy"]
git_tag_enable = true
git_release_enable = true
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"

[[package]]
name = "mefipy"
version_group = "mefikit"
changelog_update = false
publish = false
