// Umbrella header for the mefikit C++ bindings.
//
// Include this from C++ and everything below is available in namespace `mefikit`:
//
//     #include <mefikit/mefikit.hpp>
//
//     auto mesh = mefikit::UMesh::read("mesh.med");
//
// `mefikit-ffi/src/ffi.rs.h` is generated by cxx at build time from the
// `#[cxx::bridge]` in `src/ffi.rs`; it is not checked in. The CMake package
// exported by this repository adds the directory holding it to the include path,
// so the two include roots needed by this file are always set up for you.
//
// Every method that can fail throws a `rust::Error`; catch it as
// `const rust::Error &` and read `what()`. Methods documented as `noexcept`
// cannot fail.
#pragma once

#include "rust/cxx.h"
#include "mefikit-ffi/src/ffi.rs.h"

namespace mefikit {

// Factories for `TransferMethod`.
//
// cxx cannot emit free functions as members of a shared struct, so these live
// here instead. They exist so that the parameters a variant does not use stay
// zeroed; filling a `TransferMethod` in by hand works but is easy to get wrong.

// Copy the value of the source cell containing the sample point.
inline TransferMethod constant_piecewise(PointLocation point_location) {
  TransferMethod method{};
  method.kind = TransferMethodKind::ConstantPiecewise;
  method.point_location = point_location;
  method.k = 0;
  method.exponent = 0.0;
  method.weighting = DistanceWeighting::Constant;
  return method;
}

// Overlap-measure weighted average; conservative for intensive fields.
inline TransferMethod conservative_p0() {
  TransferMethod method{};
  method.kind = TransferMethodKind::ConservativeP0;
  method.point_location = PointLocation::Centroid;
  method.k = 0;
  method.exponent = 0.0;
  method.weighting = DistanceWeighting::Constant;
  return method;
}

// Shepard interpolation over the `k` nearest source cells.
inline TransferMethod inverse_distance(std::size_t k, double exponent = 2.0) {
  TransferMethod method{};
  method.kind = TransferMethodKind::InverseDistance;
  method.point_location = PointLocation::Centroid;
  method.k = k;
  method.exponent = exponent;
  method.weighting = DistanceWeighting::Constant;
  return method;
}

// Local least-squares fit over the `k` nearest source cells. `exponent` is only
// read by the InverseDistance and CompactSupport weightings.
inline TransferMethod moving_least_squares(std::size_t k,
                                           DistanceWeighting weighting,
                                           double exponent = 2.0) {
  TransferMethod method{};
  method.kind = TransferMethodKind::MovingLeastSquares;
  method.point_location = PointLocation::Centroid;
  method.k = k;
  method.exponent = exponent;
  method.weighting = weighting;
  return method;
}

} // namespace mefikit
