from collections.abc import Callable, Sequence
from typing import TypeAlias

import medcoupling as mc
import meshio as mio
import numpy as np
import numpy.typing as npt
import pyvista as pv

# --- Helper type aliases ---

Array1F: TypeAlias = npt.NDArray[np.float64]
Array2F: TypeAlias = npt.NDArray[np.float64]
Array1U: TypeAlias = npt.NDArray[np.uintp]
Array2U: TypeAlias = npt.NDArray[np.uintp]
ArrayDynF: TypeAlias = npt.NDArray[np.float64]

# Connectivity:
# - Regular: (n_elem, n_nodes_per_elem)
# - Poly: (data, offsets)
Connectivity: TypeAlias = Array2U | tuple[Array1U, Array1U]

# Anything usable where a `Field` expression is expected.
FieldInput: TypeAlias = str | float | ArrayDynF | Field

class Selection:
    def __and__(self, other: Selection) -> Selection: ...
    def __or__(self, other: Selection) -> Selection: ...
    def __xor__(self, other: Selection) -> Selection: ...
    def __sub__(self, other: Selection) -> Selection: ...
    def __invert__(self) -> Selection: ...
    def nbbox(
        self, min: Sequence[float], max: Sequence[float], all: bool
    ) -> Selection: ...
    def nrect(
        self, min: Sequence[float], max: Sequence[float], all: bool
    ) -> Selection: ...
    def nsphere(self, center: Sequence[float], r2: float, all: bool) -> Selection: ...
    def ncircle(self, center: Sequence[float], r2: float, all: bool) -> Selection: ...
    def nids(self, ids: Sequence[int], all: bool) -> Selection: ...
    def bbox(self, min: Sequence[float], max: Sequence[float]) -> Selection: ...
    def rect(self, min: Sequence[float], max: Sequence[float]) -> Selection: ...
    def sphere(self, center: Sequence[float], r2: float) -> Selection: ...
    def circle(self, center: Sequence[float], r2: float) -> Selection: ...

class Field:
    def __init__(self, any: str | float | ArrayDynF) -> None: ...
    def __add__(self, other: FieldInput) -> Field: ...
    def __sub__(self, other: FieldInput) -> Field: ...
    def __mul__(self, other: FieldInput) -> Field: ...
    def __truediv__(self, other: FieldInput) -> Field: ...
    def __radd__(self, other: FieldInput) -> Field: ...
    def __rsub__(self, other: FieldInput) -> Field: ...
    def __rmul__(self, other: FieldInput) -> Field: ...
    def __rtruediv__(self, other: FieldInput) -> Field: ...
    def abs(self) -> Field: ...
    def tan(self) -> Field: ...
    def exp(self) -> Field: ...
    def cos(self) -> Field: ...
    def sin(self) -> Field: ...
    def log10(self) -> Field: ...
    def ln(self) -> Field: ...
    def square(self) -> Field: ...
    def sqrt(self) -> Field: ...
    def __gt__(self, other: FieldInput) -> Selection: ...
    def __ge__(self, other: FieldInput) -> Selection: ...
    def __lt__(self, other: FieldInput) -> Selection: ...
    def __le__(self, other: FieldInput) -> Selection: ...

class OverlayOperation:
    IMPRINT: OverlayOperation
    UNION: OverlayOperation
    INTERSECTION: OverlayOperation
    DIFFERENCE: OverlayOperation
    SYMMETRIC_DIFFERENCE: OverlayOperation

class ConstantPiecewise:
    def __init__(self, src_mesh: UMesh, tgt_mesh: UMesh) -> None: ...
    def apply_update(
        self,
        src_mesh: UMesh,
        field_name: str,
        tgt_mesh: UMesh,
        tgt_field_name: str | None = ...,
        def_val: float = ...,
    ) -> None: ...

class DistanceWeighting:
    # `DistanceWeighting.None()` also exists at runtime, but `None` is a Python
    # keyword and cannot be spelled in a stub file.
    InverseDistance: Callable[[float], DistanceWeighting]
    Gaussian: Callable[[], DistanceWeighting]

class MovingLeastSquares:
    def __init__(
        self,
        src_mesh: UMesh,
        tgt_mesh: UMesh,
        k: int = ...,
        weighting: DistanceWeighting = ...,
    ) -> None: ...
    def apply_update(
        self,
        src_mesh: UMesh,
        field_name: str,
        tgt_mesh: UMesh,
        tgt_field_name: str | None = ...,
        def_val: float = ...,
    ) -> None: ...

class InverseDistance:
    def __init__(
        self, src_mesh: UMesh, tgt_mesh: UMesh, k: int = ..., exponent: float = ...
    ) -> None: ...
    def apply_update(
        self,
        src_mesh: UMesh,
        field_name: str,
        tgt_mesh: UMesh,
        tgt_field_name: str | None = ...,
        def_val: float = ...,
    ) -> None: ...

class ConservativeP0:
    def __init__(self, src_mesh: UMesh, tgt_mesh: UMesh) -> None: ...
    def apply_update(
        self,
        src_mesh: UMesh,
        field_name: str,
        tgt_mesh: UMesh,
        tgt_field_name: str | None = ...,
        def_val: float = ...,
        extensive: bool = ...,
    ) -> None: ...

class sel:
    @staticmethod
    def bbox(min: Sequence[float], max: Sequence[float]) -> Selection: ...
    @staticmethod
    def rect(min: Sequence[float], max: Sequence[float]) -> Selection: ...
    @staticmethod
    def sphere(center: Sequence[float], r2: float) -> Selection: ...
    @staticmethod
    def circle(center: Sequence[float], r2: float) -> Selection: ...
    @staticmethod
    def ids(eids: dict[str, Sequence[int]]) -> Selection: ...
    @staticmethod
    def nbbox(min: Sequence[float], max: Sequence[float], all: bool) -> Selection: ...
    @staticmethod
    def nrect(min: Sequence[float], max: Sequence[float], all: bool) -> Selection: ...
    @staticmethod
    def nsphere(center: Sequence[float], r2: float, all: bool) -> Selection: ...
    @staticmethod
    def ncircle(center: Sequence[float], r2: float, all: bool) -> Selection: ...
    @staticmethod
    def nids(ids: Sequence[int], all: bool) -> Selection: ...

class transfer:
    ConstantPiecewise: type[ConstantPiecewise]
    MovingLeastSquares: type[MovingLeastSquares]
    InverseDistance: type[InverseDistance]
    ConservativeP0: type[ConservativeP0]
    DistanceWeighting: type[DistanceWeighting]

class data:
    @staticmethod
    def umesh2() -> UMesh: ...
    @staticmethod
    def umesh3() -> UMesh: ...
    @staticmethod
    def cmesh3() -> UMesh: ...

def build_cmesh(*axes: Sequence[float]) -> UMesh: ...
def has(name: str) -> bool: ...

class UMesh:
    def __init__(self, coords: Array2F) -> None: ...

    # --- basic accessors ---

    def coords(self) -> Array2F: ...
    def block_types(self) -> list[str]: ...
    def blocks(self) -> dict[str, Connectivity]: ...
    def fields(self) -> dict[str, dict[str, ArrayDynF]]: ...
    def num_elements(self) -> int: ...

    # --- serialization ---

    def to_json(self) -> str: ...
    def to_json_pretty(self) -> str: ...
    @staticmethod
    def read(path: str) -> UMesh: ...
    def write(self, path: str) -> None: ...

    # --- mesh construction ---

    def add_regular_block(
        self,
        et: str,
        block: Array2U,
        fields: dict[str, ArrayDynF] | None = ...,
    ) -> None: ...
    def set_field(self, name: str, field: dict[str, ArrayDynF]) -> None: ...

    # --- topology operations ---

    def descend(
        self,
        src_dim: int | None = ...,
        target_dim: int | None = ...,
    ) -> UMesh: ...
    def descend_update(
        self,
        src_dim: int | None = ...,
        target_dim: int | None = ...,
    ) -> UMesh | None: ...
    def boundaries(
        self,
        src_dim: int | None = ...,
        target_dim: int | None = ...,
    ) -> UMesh: ...
    def boundaries_update(
        self,
        src_dim: int | None = ...,
        target_dim: int | None = ...,
    ) -> UMesh | None: ...
    def connected_components(
        self,
        src_dim: int | None = ...,
        link_dim: int | None = ...,
        with_fields: bool = ...,
    ) -> list[UMesh]: ...

    # --- measures ---

    def measure(self) -> dict[str, Array1F]: ...
    def measure_update(self) -> None: ...

    # --- geometric ops ---

    def crack(self, cut_mesh: UMesh) -> UMesh: ...
    def snap(self, reference: UMesh, eps: float = ...) -> UMesh: ...
    def merge_nodes(self, eps: float = ...) -> UMesh: ...
    def extrude(self, along: Sequence[float]) -> UMesh: ...
    def extrude_parallel(self, along: Array2F) -> UMesh: ...
    def extrude_curv(self, along: Array2F) -> UMesh: ...
    def split(self) -> UMesh: ...
    def overlay(
        self, mesh2: UMesh, operation: OverlayOperation | None = ...
    ) -> UMesh: ...

    # --- selection & evaluation ---

    def select(self, expr: Selection, with_fields: bool = ...) -> UMesh: ...
    def eval(self, expr: FieldInput) -> dict[str, ArrayDynF]: ...
    def eval_update(self, name: str, expr: FieldInput) -> None: ...

    # --- misc ---

    def __str__(self) -> str: ...

    # --- conversions ---

    def to_pyvista(
        self, dim: str | int | None = None, with_fields: Sequence[str] | bool = True
    ) -> pv.UnstructuredGrid: ...
    def to_mc(self, lev: int | None = None) -> mc.MEDCouplingUMesh: ...
    def to_meshio(self) -> mio.Mesh: ...
