from collections.abc import Sequence

from . import Selection

def bbox(min: Sequence[float], max: Sequence[float]) -> Selection: ...
def rect(min: Sequence[float], max: Sequence[float]) -> Selection: ...
def sphere(center: Sequence[float], r2: float) -> Selection: ...
def circle(center: Sequence[float], r2: float) -> Selection: ...
def ids(eids: dict[str, Sequence[int]]) -> Selection: ...
def nbbox(min: Sequence[float], max: Sequence[float], all: bool) -> Selection: ...
def nrect(min: Sequence[float], max: Sequence[float], all: bool) -> Selection: ...
def nsphere(center: Sequence[float], r2: float, all: bool) -> Selection: ...
def ncircle(center: Sequence[float], r2: float, all: bool) -> Selection: ...
def nids(ids: Sequence[int], all: bool) -> Selection: ...
def group(name: str) -> Selection: ...
def exclude_group(name: str) -> Selection: ...
def types(types: Sequence[str]) -> Selection: ...
def all() -> Selection: ...
