# on: [pull_request]
# name: benchmark pull requests
# jobs:
#   runBenchmark:
#     name: run benchmark
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install Valgrind
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y valgrind
#       - uses: taiki-e/install-action@cargo-binstall
#       - name: Install gungraun-runner
#         run: |
#           version=$(cargo metadata --format-version=1 |\
#             jq '.packages[] | select(.name == "gungraun").version' |\
#             tr -d '"'
#           )
#           cargo binstall --no-confirm gungraun-runner --version $version
#       - uses: boa-dev/criterion-compare-action@v3
#         with:
#           cwd: "meficore"
#           # # Optional. Compare only this package
#           # package: "example-package"
#           # # Optional. Compare only this benchmark target
#           benchName: "submesh_analytics"
#           # # Optional. Disables the default features of a crate
#           # defaultFeatures: false
#           # # Optional. Features activated in the benchmark
#           # features: "async,tokio-support"
#           # Needed. The name of the branch to compare with. This default uses the branch which is being pulled against
#           branchName: ${{ github.base_ref }}
#           # Optional. Default is `${{ github.token }}`.
#           token: ${{ secrets.GITHUB_TOKEN }}
